# Generated by Django 5.0.6 on 2024-06-03 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('estudiante', models.CharField(max_length=100)),
                ('tema', models.CharField(choices=[('Tecnología', 'Tecnología'), ('Educación', 'Educación'), ('Medio Ambiente', 'Medio Ambiente'), ('Recreación', 'Recreación'), ('Social', 'Social')], max_length=100)),
                ('patrocinado', models.BooleanField(default=False)),
                ('profesor_patrocinador', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesor', 'Profesor')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
